name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # sesuaikan versi .NET kamu

    - name: Restore dependencies
      run: dotnet restore ./Perpustakaan/Perpustakaan.csproj

    - name: Build project
      run: dotnet build ./Perpustakaan/Perpustakaan.csproj --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ./Perpustakaan.Tests/Perpustakaan.Tests.csproj --no-build --verbosity normal
